In [3]:
!pip install tensorflow

In [4]:
import tensorflow as tf
print(tf.__version__)


2.19.0


In [5]:
a=tf.constant(10)
b=tf.constant(20)
print(a+b)



tf.Tensor(30, shape=(), dtype=int32)


In [6]:
v=tf.constant([1,2,3,4])

In [7]:
print(v)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [8]:
m=tf.constant([[1,2],[3,4]])

In [9]:
print(m)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
t3 = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(t3)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [11]:
a1=tf.constant([1,2,3,4])
print(a1.dtype,a1.shape,tf.rank(a1))

<dtype: 'int32'> (4,) tf.Tensor(1, shape=(), dtype=int32)


In [12]:
a=tf.constant([10,20,30])
b=tf.constant([50,60,70])
c=tf.add(a,b)
print(c)

d=tf.subtract(a,b)
print(d)

e=tf.multiply(a,b)
print(e)

f=tf.divide(a,b)
print(f)

g=tf.pow(a,2)
print(g)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor([-40 -40 -40], shape=(3,), dtype=int32)
tf.Tensor([ 500 1200 2100], shape=(3,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143], shape=(3,), dtype=float64)
tf.Tensor([100 400 900], shape=(3,), dtype=int32)


In [13]:
import numpy as np
np_array = ([[1,2,3],[4,5,6]])

tensor=tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
